# backend/alembic/script.py.mako
"""add_vm_gateway_and_dns_fields

Revision ID: 4ca18a996169
Revises: a1b2c3d4e5f6
Create Date: 2026-01-13 21:30:27.339787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca18a996169'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vms', sa.Column('gateway', sa.String(length=15), nullable=True))
    op.add_column('vms', sa.Column('dns_servers', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vms', 'dns_servers')
    op.drop_column('vms', 'gateway')
    # ### end Alembic commands ###
