# backend/alembic/script.py.mako
"""add_display_type_to_vm

Revision ID: 55ac0fc66160
Revises: d8d8fb1113af
Create Date: 2026-01-12 21:45:48.087425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ac0fc66160'
down_revision: Union[str, None] = 'd8d8fb1113af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vms', sa.Column('display_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vms', 'display_type')
    # ### end Alembic commands ###
