# backend/alembic/script.py.mako
"""add connections table

Revision ID: 5bd854c4ed56
Revises: 8eb1be82970a
Create Date: 2026-01-12 20:21:00.289679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd854c4ed56'
down_revision: Union[str, None] = '8eb1be82970a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('range_id', sa.Uuid(), nullable=False),
    sa.Column('src_vm_id', sa.Uuid(), nullable=True),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=False),
    sa.Column('dst_vm_id', sa.Uuid(), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.Enum('TCP', 'UDP', 'ICMP', name='connectionprotocol'), nullable=False),
    sa.Column('state', sa.Enum('ESTABLISHED', 'CLOSED', 'TIMEOUT', 'RESET', name='connectionstate'), nullable=False),
    sa.Column('bytes_sent', sa.Integer(), nullable=False),
    sa.Column('bytes_received', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dst_vm_id'], ['vms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_vm_id'], ['vms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_dst_vm_id'), 'connections', ['dst_vm_id'], unique=False)
    op.create_index(op.f('ix_connections_range_id'), 'connections', ['range_id'], unique=False)
    op.create_index(op.f('ix_connections_src_vm_id'), 'connections', ['src_vm_id'], unique=False)
    op.create_index(op.f('ix_connections_state'), 'connections', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_state'), table_name='connections')
    op.drop_index(op.f('ix_connections_src_vm_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_range_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_dst_vm_id'), table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
