# backend/alembic/script.py.mako
"""add_linux_vm_fields_to_templates

Revision ID: 89e9aed193fa
Revises: f1a2b3c4d5e6
Create Date: 2026-01-13 07:09:16.570811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e9aed193fa'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: The user_attributes indexes were already dropped in a previous migration, skip if they don't exist
    try:
        op.drop_index('ix_user_attributes_type_value', table_name='user_attributes')
    except Exception:
        pass  # Index may not exist
    try:
        op.drop_index('ix_user_attributes_user_id', table_name='user_attributes')
    except Exception:
        pass  # Index may not exist

    # Create the vmtype enum first (PostgreSQL requires explicit enum creation)
    vmtype_enum = sa.Enum('CONTAINER', 'LINUX_VM', 'WINDOWS_VM', name='vmtype')
    vmtype_enum.create(op.get_bind(), checkfirst=True)

    # Add vm_type with server_default to handle existing rows, then remove the default
    op.add_column('vm_templates', sa.Column('vm_type', vmtype_enum, nullable=False, server_default='CONTAINER'))
    op.alter_column('vm_templates', 'vm_type', server_default=None)

    op.add_column('vm_templates', sa.Column('linux_distro', sa.String(length=50), nullable=True))
    op.add_column('vm_templates', sa.Column('boot_mode', sa.String(length=10), nullable=True))
    op.add_column('vm_templates', sa.Column('disk_type', sa.String(length=10), nullable=True))
    op.add_column('vms', sa.Column('linux_distro', sa.String(length=50), nullable=True))
    op.add_column('vms', sa.Column('boot_mode', sa.String(length=10), nullable=True))
    op.add_column('vms', sa.Column('disk_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vms', 'disk_type')
    op.drop_column('vms', 'boot_mode')
    op.drop_column('vms', 'linux_distro')
    op.drop_column('vm_templates', 'disk_type')
    op.drop_column('vm_templates', 'boot_mode')
    op.drop_column('vm_templates', 'linux_distro')
    op.drop_column('vm_templates', 'vm_type')

    # Drop the vmtype enum
    vmtype_enum = sa.Enum('CONTAINER', 'LINUX_VM', 'WINDOWS_VM', name='vmtype')
    vmtype_enum.drop(op.get_bind(), checkfirst=True)

    op.create_index('ix_user_attributes_user_id', 'user_attributes', ['user_id'], unique=False)
    op.create_index('ix_user_attributes_type_value', 'user_attributes', ['attribute_type', 'attribute_value'], unique=False)
    # ### end Alembic commands ###
