# backend/alembic/script.py.mako
"""add event_logs table

Revision ID: 8eb1be82970a
Revises: a3bf687a900a
Create Date: 2026-01-12 20:07:40.083088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb1be82970a'
down_revision: Union[str, None] = 'a3bf687a900a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_logs',
    sa.Column('range_id', sa.Uuid(), nullable=False),
    sa.Column('vm_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('RANGE_DEPLOYED', 'RANGE_STARTED', 'RANGE_STOPPED', 'RANGE_TEARDOWN', 'VM_CREATED', 'VM_STARTED', 'VM_STOPPED', 'VM_RESTARTED', 'VM_ERROR', 'SNAPSHOT_CREATED', 'SNAPSHOT_RESTORED', 'ARTIFACT_PLACED', 'INJECT_EXECUTED', 'INJECT_FAILED', 'CONNECTION_ESTABLISHED', 'CONNECTION_CLOSED', name='eventtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_range_id'), 'event_logs', ['range_id'], unique=False)
    op.create_index(op.f('ix_event_logs_vm_id'), 'event_logs', ['vm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_logs_vm_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_range_id'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_table('event_logs')
    # ### end Alembic commands ###
