# backend/alembic/script.py.mako
"""Initial schema

Revision ID: a3bf687a900a
Revises: 
Create Date: 2026-01-12 17:22:01.517934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3bf687a900a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ENGINEER', 'FACILITATOR', 'EVALUATOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('artifacts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.Enum('EXECUTABLE', 'SCRIPT', 'DOCUMENT', 'ARCHIVE', 'CONFIG', 'OTHER', name='artifacttype'), nullable=False),
    sa.Column('malicious_indicator', sa.Enum('SAFE', 'SUSPICIOUS', 'MALICIOUS', name='maliciousindicator'), nullable=False),
    sa.Column('ttps', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_name'), 'artifacts', ['name'], unique=False)
    op.create_index(op.f('ix_artifacts_sha256_hash'), 'artifacts', ['sha256_hash'], unique=False)
    op.create_table('ranges',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'DEPLOYING', 'RUNNING', 'STOPPED', 'ARCHIVED', 'ERROR', name='rangestatus'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranges_name'), 'ranges', ['name'], unique=False)
    op.create_table('vm_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('os_type', sa.Enum('WINDOWS', 'LINUX', name='ostype'), nullable=False),
    sa.Column('os_variant', sa.String(length=100), nullable=False),
    sa.Column('base_image', sa.String(length=255), nullable=False),
    sa.Column('default_cpu', sa.Integer(), nullable=False),
    sa.Column('default_ram_mb', sa.Integer(), nullable=False),
    sa.Column('default_disk_gb', sa.Integer(), nullable=False),
    sa.Column('config_script', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vm_templates_name'), 'vm_templates', ['name'], unique=False)
    op.create_table('networks',
    sa.Column('range_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subnet', sa.String(length=18), nullable=False),
    sa.Column('gateway', sa.String(length=15), nullable=False),
    sa.Column('dns_servers', sa.String(length=255), nullable=True),
    sa.Column('isolation_level', sa.Enum('COMPLETE', 'CONTROLLED', 'OPEN', name='isolationlevel'), nullable=False),
    sa.Column('docker_network_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vms',
    sa.Column('range_id', sa.Uuid(), nullable=False),
    sa.Column('network_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=63), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=False),
    sa.Column('ram_mb', sa.Integer(), nullable=False),
    sa.Column('disk_gb', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CREATING', 'RUNNING', 'STOPPED', 'ERROR', name='vmstatus'), nullable=False),
    sa.Column('container_id', sa.String(length=64), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['range_id'], ['ranges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['vm_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact_placements',
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('vm_id', sa.Uuid(), nullable=False),
    sa.Column('target_path', sa.String(length=500), nullable=False),
    sa.Column('placement_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'PLACED', 'VERIFIED', 'FAILED', name='placementstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('vm_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('docker_image_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots')
    op.drop_table('artifact_placements')
    op.drop_table('vms')
    op.drop_table('networks')
    op.drop_index(op.f('ix_vm_templates_name'), table_name='vm_templates')
    op.drop_table('vm_templates')
    op.drop_index(op.f('ix_ranges_name'), table_name='ranges')
    op.drop_table('ranges')
    op.drop_index(op.f('ix_artifacts_sha256_hash'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_name'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
