# backend/alembic/script.py.mako
"""add_windows_vm_parameters

Revision ID: d8d8fb1113af
Revises: b2c8f4a1d3e5
Create Date: 2026-01-12 21:39:20.482274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d8fb1113af'
down_revision: Union[str, None] = 'b2c8f4a1d3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vms', sa.Column('windows_version', sa.String(length=10), nullable=True))
    op.add_column('vms', sa.Column('windows_username', sa.String(length=64), nullable=True))
    op.add_column('vms', sa.Column('windows_password', sa.String(length=128), nullable=True))
    op.add_column('vms', sa.Column('iso_url', sa.String(length=512), nullable=True))
    op.add_column('vms', sa.Column('iso_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vms', 'iso_path')
    op.drop_column('vms', 'iso_url')
    op.drop_column('vms', 'windows_password')
    op.drop_column('vms', 'windows_username')
    op.drop_column('vms', 'windows_version')
    # ### end Alembic commands ###
